-- 删除 C##CAR.ACCEPTANCE_OF_SWITCH_REQUESTS 的数据
DELETE FROM C##CAR.ACCEPTANCE_OF_SWITCH_REQUESTS;

-- 删除 C##CAR.COMPLETION_OF_MAINTENANCE 的数据
DELETE FROM C##CAR.COMPLETION_OF_MAINTENANCE;

-- 删除 C##CAR.BATTERY_BATTERY_REPLACING_SITES 的数据
DELETE FROM C##CAR.BATTERY_BATTERY_REPLACING_SITES;

-- 删除 C##CAR.STAFF_IN_BATTERY_REPLACING_SITES 的数据
DELETE FROM C##CAR.STAFF_IN_BATTERY_REPLACING_SITES;

-- 删除 C##CAR.MAINTENANCE_ITEMS 的数据
DELETE FROM C##CAR.MAINTENANCE_ITEMS;

-- 删除 C##CAR.SWITCH_REQUESTS 的数据
DELETE FROM C##CAR.SWITCH_REQUESTS;

-- 删除 C##CAR.VEHICLES 的数据
DELETE FROM C##CAR.VEHICLES;

-- 删除 C##CAR.PERFORMANCES 的数据
DELETE FROM C##CAR.PERFORMANCES;

-- 删除 C##CAR.SWITCH_LOG 的数据
DELETE FROM C##CAR.SWITCH_LOG;

-- 删除 C##CAR.BATTERY_BATTERY_REPLACING_SITES 的数据
DELETE FROM C##CAR.BATTERY_BATTERY_REPLACING_SITES;

-- 删除 C##CAR.ANNOUNCEMENT 的数据
DELETE FROM C##CAR.ANNOUNCEMENT;

-- 删除 C##CAR.BATTERY 的数据
DELETE FROM C##CAR.BATTERY;

-- 删除 C##CAR.BATTERY_MODEL 的数据
DELETE FROM C##CAR.BATTERY_MODEL;

-- 删除 C##CAR.OWNERS 的数据
DELETE FROM C##CAR.OWNERS;

-- 删除 C##CAR.STAFF 的数据
DELETE FROM C##CAR.STAFF;

-- 删除 C##CAR.VIHECLE_PARAM 的数据
DELETE FROM C##CAR.VEHICLE_PARAM;

-- 删除 C##CAR.BATTERY_REPLACING_SITES 的数据
DELETE FROM C##CAR.BATTERY_REPLACING_SITES;