-- 删除 C##CAR.SWITCH_REQUEST_EMPLOYEE 的数据
DELETE FROM C##CAR.SWITCH_REQUEST_EMPLOYEE;

-- 删除 C##CAR.MAINTENANCE_ITEM_EMPLOYEE 的数据
DELETE FROM C##CAR.MAINTENANCE_ITEM_EMPLOYEE;

-- 删除 C##CAR.BATTERY_SWITCH_STATION 的数据
DELETE FROM C##CAR.BATTERY_SWITCH_STATION;

-- 删除 C##CAR.EMPLOYEE_SWITCH_STATION 的数据
DELETE FROM C##CAR.EMPLOYEE_SWITCH_STATION;

-- 删除 C##CAR.MAINTENANCE_ITEM 的数据
DELETE FROM C##CAR.MAINTENANCE_ITEM;

-- 删除 C##CAR.SWITCH_REQUESTS 的数据
DELETE FROM C##CAR.SWITCH_REQUESTS;

-- 删除 C##CAR.VEHICLE 的数据
DELETE FROM C##CAR.VEHICLE;

-- 删除 C##CAR.KPI 的数据
DELETE FROM C##CAR.KPI;

-- 删除 C##CAR.SWITCH_LOG 的数据
DELETE FROM C##CAR.SWITCH_LOG;

-- 删除 C##CAR.BATTERY_SWITCH_STATION 的数据
DELETE FROM C##CAR.BATTERY_SWITCH_STATION;

-- 删除 C##CAR.NEWS 的数据
DELETE FROM C##CAR.NEWS;

-- 删除 C##CAR.BATTERY 的数据
DELETE FROM C##CAR.BATTERY;

-- 删除 C##CAR.BATTERY_TYPE 的数据
DELETE FROM C##CAR.BATTERY_TYPE;

-- 删除 C##CAR.VEHICLE_OWNER 的数据
DELETE FROM C##CAR.VEHICLE_OWNER;

-- 删除 C##CAR.EMPLOYEE 的数据
DELETE FROM C##CAR.EMPLOYEE;

-- 删除 C##CAR.VIHECLE_PARAM 的数据
DELETE FROM C##CAR.VEHICLE_PARAM;

-- 删除 C##CAR.SWITCH_STATION 的数据
DELETE FROM C##CAR.SWITCH_STATION;