-- É¾³ý±í C##CAR.ACCEPTANCE_OF_SWITCH_REQUESTS
DROP TABLE C##CAR.ACCEPTANCE_OF_SWITCH_REQUESTS CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.COMPLETION_OF_MAINTENANCE
DROP TABLE C##CAR.COMPLETION_OF_MAINTENANCE CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.MAINTENANCE_ITEMS
DROP TABLE C##CAR.MAINTENANCE_ITEMS CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.STAFF_IN_BATTERY_REPLACING_SITES
DROP TABLE C##CAR.STAFF_IN_BATTERY_REPLACING_SITES CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.VEHICLES
DROP TABLE C##CAR.VEHICLES CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.SWITCH_REQUESTS
DROP TABLE C##CAR.SWITCH_REQUESTS CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.PERFORMANCES
DROP TABLE C##CAR.PERFORMANCES CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.SWITCH_LOG
DROP TABLE C##CAR.SWITCH_LOG CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.BATTERY_BATTERY_REPLACING_SITES
DROP TABLE C##CAR.BATTERY_BATTERY_REPLACING_SITES CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.ANNOUNCEMENT
DROP TABLE C##CAR.ANNOUNCEMENT CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.STAFF
DROP TABLE C##CAR.STAFF CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.OWNERS
DROP TABLE C##CAR.OWNERS CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.VEHICLE_PARAM
DROP TABLE C##CAR.VEHICLE_PARAM CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.BATTERY
DROP TABLE C##CAR.BATTERY CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.BATTERY_MODEL
DROP TABLE C##CAR.BATTERY_MODEL CASCADE CONSTRAINTS;

-- É¾³ý±í C##CAR.BATTERY_REPLACING_SITES
DROP TABLE C##CAR.BATTERY_REPLACING_SITES CASCADE CONSTRAINTS;

-- É¾³ýËùÓÐ´¥·¢Æ÷
DROP TRIGGER C##CAR.trg_cascade_update_battery;
DROP TRIGGER C##CAR.trg_bat_bat_replacing_sites_battery;
DROP TRIGGER C##CAR.trg_bat_bat_replacing_sites_site;
DROP TRIGGER C##CAR.trg_performances_staff;
DROP TRIGGER C##CAR.trg_vehicles_owner;
DROP TRIGGER C##CAR.trg_vehicles_vehicle_param;
DROP TRIGGER C##CAR.trg_vehicles_battery;
DROP TRIGGER C##CAR.trg_maintenance_items_vehicle;
DROP TRIGGER C##CAR.trg_staff_in_battery_replacing_sites_employee;
DROP TRIGGER C##CAR.trg_staff_in_battery_replacing_sites_site;
DROP TRIGGER C##CAR.trg_completion_of_maintenance_staff;
DROP TRIGGER C##CAR.trg_completion_of_maintenance_maintenance_item;
DROP TRIGGER C##CAR.trg_acceptance_of_switch_requests_employee;
DROP TRIGGER C##CAR.trg_switch_requests_vehicles;
DROP TRIGGER C##CAR.trg_switch_requests_acceptance;
DROP TRIGGER C##CAR.trg_switch_log_vehicles;
DROP TRIGGER C##CAR.trg_switch_log_staff;
DROP TRIGGER C##CAR.trg_switch_log_battery_in;
DROP TRIGGER C##CAR.trg_switch_log_battery_out;
DROP TRIGGER C##CAR.trg_switch_log_switch_requests_lon;
DROP TRIGGER C##CAR.trg_switch_log_switch_requests_lat;